Update Dockerfiles and GitHub Actions workflows for improved build efficiency and clarity
- Refactored Dockerfiles for multiple services to optimize build stages and reduce image sizes.
- Updated GitHub Actions workflows to streamline deployment processes, including environment variable management and build steps.
- Removed unnecessary dependencies and improved caching strategies in Dockerfiles for faster builds.

diff --git a/post/Dockerfile b/post/Dockerfile
--- a/post/Dockerfile
+++ b/post/Dockerfile
@@ -1,24 +1,35 @@
 FROM eclipse-temurin:21-jdk-alpine as build
 WORKDIR /workspace/app
 
-# Install Maven
+# Install Maven and use --no-cache to avoid additional layer
 RUN apk add --no-cache maven
 
 COPY pom.xml .
-# to speed up the build process, we cache the maven download of dependencies
-RUN mvn install -DskipTests || true
+# Cache maven dependencies
+RUN mvn dependency:go-offline || true
+
 COPY src src
 
-# Build the application
-RUN mvn install -DskipTests
-RUN mkdir -p target/dependency && (cd target/dependency; jar -xf ../*.jar)
+# Build the application and clean up Maven cache
+RUN mvn package -DskipTests \
+    && mkdir -p target/dependency \
+    && (cd target/dependency; jar -xf ../*.jar) \
+    && rm -rf /root/.m2/repository
 
+# Smaller runtime image
 FROM eclipse-temurin:21-jre-alpine
 VOLUME /tmp
 ARG DEPENDENCY=/workspace/app/target/dependency
+
+# Copy only the necessary files
 COPY --from=build ${DEPENDENCY}/BOOT-INF/lib /app/lib
 COPY --from=build ${DEPENDENCY}/META-INF /app/META-INF
 COPY --from=build ${DEPENDENCY}/BOOT-INF/classes /app
+
+# Use a non-root user for better security
+RUN addgroup -S appgroup && adduser -S appuser -G appgroup
+USER appuser
+
 ENTRYPOINT ["java","-cp","app:app/lib/*","com.okblog.post.PostServiceApplication"]
 
 EXPOSE 8081 
